from backend.app.models.audit_log import AuditLog
from backend.app.models.detail_nilai import DetailNilai
from backend.app.models.dosen import Dosen
from backend.app.models.grade import Grade
from backend.app.models.kelas import Kelas
from backend.app.models.komponen_nilai import KomponenNilai
from backend.app.models.krs import KRS
from backend.app.models.mahasiswa import Mahasiswa
from backend.app.models.matakuliah import MataKuliah
from backend.app.models.nilai import Nilai
from backend.app.models.notifikasi import Notifikasi
from backend.app.models.program_studi import ProgramStudi
from backend.app.models.role import Role
from backend.app.models.tahun_ajaran import TahunAjaran
from backend.app.models.user import User
